name: 'dbt_project' # Mantenha o nome que você escolheu no init
version: '1.0.0'

profile: 'dbt_project' # Certifique-se que o nome aqui é o mesmo do seu profiles.yml

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# CONFIGURAÇÃO DOS MODELOS
models:
  dbt_project: # Nome do seu projeto (deve ser igual ao 'name' lá no topo)
    
    # Camada de entrada (Ponte com o MinIO)
    staging:
      +materialized: view    # Criar como View é mais rápido e economiza espaço
      +schema: staging

    # Camada de negócio (Onde as traduções que fizemos acontecem)
    refined:
      +materialized: table   # Criar como Tabela torna suas análises no EDA muito mais rápidas
      +schema: refined