version: 2

sources:
  - name: minio_raw
    loader: duckdb
    tables:
      - name: censo_trusted_parquet
        meta:
          external_location: "s3://trusted/censo_escolar/censo_trusted.parquet"